### ISSUE TITLE
update README to reflect changes in Tauri and rust projects

### ISSUE THREAD

**Issue by alf5** [dancixx/rust-sql#8]
A bit of feedback:
This project looked interesting and wanted to check it out. Currently there is a problem cloning it.
There are a couple of doc errors and, maybe, an installation error.

1. `tuari.studio` site is no longer used for docs. "This repository has been archived by the owner on May 23, 2020."
1. `cargo install` produces the error: 
   `error: Using `cargo install` to install the binaries from the package in current working directory is no longer supported, use `cargo install --path .` instead. Use `cargo build` if you want to simply build the package.` 
   - this should be updated to reflect the intended actions.
   - if the intended action is `cargo install --path .` then it currently produces an error :(

**Comment by dancixx** [comment]
@alf5 thanks for reporting this. I have updated [this part](https://github.com/dancixx/rust-sql?tab=readme-ov-file#getting-started) of the readme.md. Please let me know if you have any further issues.
